# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: suisei-cn/actions-download-file@v1
        id: downloadfile
        name: Download Build Environment
        with:
          url: "https://deaod.de/ut99/IG+BuildEnv_v469b.7z"
          target: .
          
      - name: Extract Build Environment
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ${{ steps.downloadfile.outputs.filename }}

      - name: Checkout IG+
        uses: actions/checkout@v2
        with:
          path: InstaGibPlus9/

      # Runs a single command using the runners shell
      - name: Build IG+
        run: InstaGibPlus9/build.bat

      - name: Save UCC.log
        if: ${{ success() == false }}
        uses: actions/upload-artifact@v2
        with:
          name: ucc-output
          path: System/UCC.log

      - name: Create IG+ Package
        if: ${{ success() }}
        uses: papeloto/action-zip@v1
        with:
          files: InstaGibPlus9/System/ InstaGibPlus9/LICENSE InstaGibPlus9/README.md
          recursive: true
          dest: InstaGibPlus9.zip

      - name: Save IG+ Package
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: InstaGibPlus9.zip
