# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: release-downloader
        uses: robinraju/release-downloader@v1.2
        with:
          repository: OldUnreal/UnrealTournamentPatches
          tag: v469b
          fileName: OldUnreal-UTPatch469b-Windows.zip
          out-file-path: .
          
      - name: extract-7z-action
        # You may pin to the exact commit or the version.
        # uses: DuckSoft/extract-7z-action@6eaaa506b410f047eaa9b22498696aad1e19a834
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          # archive path to extract
          pathSource: OldUnreal-UTPatch469b-Windows.zip
          # path to place the extract
          pathTarget: .
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: InstaGibPlus9/

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: InstaGibPlus9/build.bat

      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
